#! /bin/bash

dir=$(dirname "$0")

DB="povoconnect_test"
HOST="127.0.0.1"

createdb $DB
psql -h $HOST -q -f $dir/plpgunit/install/0.uninstall-unit-test.sql $DB > /dev/null 2>&1
psql -h $HOST -q -f $dir/plpgunit/install/1.install-unit-test.sql $DB > /dev/null 2>&1
psql -h $HOST -q -f $dir/factories.sql $DB
psql -h $HOST -q -f $dir/schema.sql $DB
psql -h $HOST -q -f $dir/schema.test.sql $DB


result=$(psql -h $HOST -q -c "SELECT * FROM unit_tests.begin()" $DB)

red='\033[0;31m'
green='\033[0;32m'
nc='\033[0m'

re="Test completed on (.*) N"
if [[ $result =~ $re ]]; then
	printf "${red}fail${nc}\n\n"
	exit 1
fi

printf "${green}pass${nc}\n"
